### ISSUE TITLE
Use on static map

### ISSUE THREAD

**Issue by popovae** [johnboiles/JBDaylightOverlay#2]
Hello!

I wanted to say that the job you've done is really great, nice calculations. The question I have is - is there any way to remake it to use on static map (picture - UIImage for example) The reason I ask is because there is no need to use internet connection then to download map and it will give more abilities to use this   controller... Anyway, maybe you will give me a clue how to do such thing, or maybe help with it for some reward:)

**Comment by johnboiles** [comment]
Thanks!

Don't think there's a simple way to make it work because I don't think [`MKMapSnapshotter`](https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKMapSnapshotter_class/index.html) supports `MKOverlayView`s. You could probably do something similar to [this](http://stackoverflow.com/questions/22692449/creating-an-mkmapsnapshotter-with-an-mkpolylinerenderer): render the map from `MKMapSnapshotter` and then render the `JBDaylightOverlay` in core graphics on top of the map snapshot.

Let me know if you get it to work. I'd be interested to know!

**Comment by chiragIOS** [comment]
can we use this in googlemap ?

**Comment by johnboiles** [comment]
I doubt the Google Maps sdk supports `MKOverlayView`. Read their docs. I'm sure it'd be possible to take the meat of this code and adapt it to work with whatever APIs the Google Maps SDK provides
